### ISSUE TITLE
Support label prop on Input controls

### ISSUE THREAD

**Issue by LucaT1** [slupjs/slup#19]
As in HTML, you can provide a `<label>` for an input component, in the `@slup/controls` package should enable the users to provide a label/description prop. This prop should generate a Label alongside the control component that should fire linked input as a normal click would.

Example:
```html
<Checkbox label='Whatever' />
```

The user should be able to define the direction of this element by supplying the `labeld`(which stands for direction) prop.

**Comment by Gejsi** [comment]
Instead of using two props as you said I'd rather use one single prop.
This is how you suggested doing
```js
<Checkbox labeld={right} label='Whatever' />
```

This is how I suggest doing

```js
<Checkbox rightLabel='Whatever' />
```

I think the second example is much more intuitive than the first one

**Comment by LucaT1** [comment]
It has been done in #35, closing off
